services:
  univ:
    image: uni:latest
    container_name: univ

    ports:
      - "8080:80"

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

    environment:
      TZ: Asia/Dhaka

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"