apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: univercity-alerts
  namespace: monitoring

spec:
  groups:
  - name: univercity.rules

    rules:

    - alert: FrontendDown
      expr: kube_deployment_status_replicas_available{deployment="uni-frontend"} < 1
      for: 1m

      labels:
        severity: critical

      annotations:
        summary: Univercity Frontend Down
        description: No available frontend replicas.

    - alert: FrontendHighCPU
      expr: sum(rate(container_cpu_usage_seconds_total{namespace="univercity"}[5m])) > 0.5
      for: 5m

      labels:
        severity: warning

      annotations:
        summary: High CPU Usage
        description: Frontend CPU usage is above threshold.

    - alert: FrontendHighMemory
      expr: sum(container_memory_usage_bytes{namespace="univercity"}) > 500000000
      for: 5m

      labels:
        severity: warning

      annotations:
        summary: High Memory Usage
        description: Frontend memory usage is above threshold.

    - alert: PodRestarting
      expr: increase(kube_pod_container_status_restarts_total{namespace="univercity"}[10m]) > 0
      for: 1m

      labels:
        severity: warning

      annotations:
        summary: Pod Restart Detected
        description: One or more containers restarted recently.