apiVersion: v1
kind: Service

metadata:
  name: uni-service
  namespace: univercity

spec:
  type: ClusterIP

  selector:
    app: uni-frontend

  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP