apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: univercity-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_GIT_REPO_URL
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: univercity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
