apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: univercity-frontend

  labels:
    app.kubernetes.io/name: univercity
    app.kubernetes.io/component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: univercity
      app.kubernetes.io/component: frontend
