apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: univercity
resources:
  - ../../base
patches:
  - path: patch-ingress.yaml
  - path: patch-hpa.yaml
images:
  - name: ghcr.io/REPLACE_ORG/univercity-frontend
    newTag: staging
