apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: univercity

resources:
  - ../../base

patches:

  - path: patch-hpa.yaml
images:
  - name: ponkoog/univercity
    newTag: v1.0.2